// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdfsbrnmxrdgbhhnicbl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkZnNicm5teHJkZ2JoaG5pY2JsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NzkwMTcsImV4cCI6MjA2NTU1NTAxN30.V55BoV7iK7WG6C7yqzVFQo7iWpsoNgg8jDnDxJv3d14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);